class UserException(Exception):
    pass


class UserNotFound(UserException):
    pass
